apiVersion: v1
kind: Service
metadata:
  name: pcam-api
  labels:
    app: pcam-api
spec:
  selector:
    app: pcam-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
